import React, { useEffect, useState } from 'react';
import Header from '../Header';
import Row from '../Row';
import Input from '../Input';
import Action from '../Action';
import Helper from '../Helper';


export default function General(props:any) {

  const data = props.data;
  const[isComplete, setIsComplete] = useState(data.general.isComplete);

  if(data.general.id == null) {
    data.general.id = "ID-" + Math.floor(Math.random() * Math.floor(999999));
  }

  function sendUp(){
    if(!Object.values(data.general).includes(null)){
      data.general.isComplete = true;
      setIsComplete(true);
    }

    else{
      data.general.isComplete = false;
      setIsComplete(false);
    }

    props.update(data);
    console.log(data)
  }

  const container = {
    width: "100%",
    height: "100%",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column"
  } as React.CSSProperties;

  const content = {
    height: "100%",
    display: "flex",
    flexDirection: "column",
    padding: "12px 0px 12px 0px",
    overflowX: "hidden",
    overflowY: "scroll",
    alignItems: "center",
    borderBottom: "1px solid var(--color-contrast-low)"
  } as React.CSSProperties;


  return (
    <div style={container}>
      <Header
      text="General"
      subtext="In this section you are asked to complete your general information.
      The information will be used to identify correlations and patterns between you and the other participants.
      After you finish this section please click 'Next' to proceed to the trait analysis and please let the examiner know if you have any questions."
      />

      <div style={content}>
        <Row
          margin="8px 0px 8px 0px"
          padding="0px 0px 0px 44px"
          >
          <Input
            value={data.general.id}
            type="field"
            label="ID"
            placeholder="Please contact the examinator if this filed is empty"
            fieldWidth="400px"
            disabled={true}
            labelWidth="180px"
            onUpdate={(event:any)=> {data.general.gender = event; sendUp()}}
          />
          <Helper
            text="This field is autogenerated. You can keep the id to identify your report to the examiner."
            size="32px"
            borderRadius= "0px 3px 3px 0px"
          />
        </Row>
        <Row
          margin="8px 0px 8px 0px"
          padding="0px 0px 0px 44px"
          >
          <Input
            type="field"
            value={data.general.name}
            label="Name"
            placeholder="Your name..."
            fieldWidth="400px"
            labelWidth="180px"
            onUpdate={(event:any)=> data.general.name = event}
          />
          <Helper
            text="Input your name."
            size="32px"
            borderRadius= "0px 3px 3px 0px"
          />
        </Row>
        <Row
          margin="8px 0px 8px 0px"
          padding="0px 0px 0px 44px"
          >
          <Input
          value={data.general.age}
            type="field"
            label="Age"
            placeholder="Your age..."
            fieldWidth="400px"
            labelWidth="180px"
            onUpdate={(event:any)=> data.general.age = event}
          />

          <Helper
            text="Insert your current age as a number [there is no need for a birth date]."
            size="32px"
            borderRadius= "0px 3px 3px 0px"
          />

        </Row>
        <Row
          margin="8px 0px 8px 0px"
          padding="0px 0px 0px 44px"
          >
          <Input
            value={data.general.gender}
            type="field"
            label="Gender"
            placeholder="Your gender..."
            fieldWidth="400px"
            labelWidth="180px"
            onUpdate={(event:any)=> {data.general.gender = event; sendUp()}}
          />
          <Helper
            text="Input your biological gender (i.e. male/female)."
            size="32px"
            borderRadius= "0px 3px 3px 0px"
          />
        </Row>

        <Row
          margin="8px 0px 8px 0px"
          padding="0px 0px 0px 44px"
          >
          <Input
            value={data.general.nationality}
            type="field"
            label="Nationality & Residence"
            placeholder="i.e. British(citizen - born), Italy(resident - 4 years)"
            fieldWidth="400px"
            labelWidth="180px"
            onUpdate={(event:any)=> {data.general.nationality = event; sendUp()}}
          />
          <Helper
            text="You nationality, and if applicable, the other countries that you have lived in. If multiple, please specify and add an approximation of the residence timespan."
            size="32px"
            borderRadius= "0px 3px 3px 0px"
          />
        </Row>

        <Row
          margin="8px 0px 8px 0px"
          padding="0px 0px 0px 44px"
          >
          <Input
            value={data.general.education}
            type="field"
            label="Education"
            placeholder="i.e. MArch, MBA"
            fieldWidth="400px"
            labelWidth="180px"
            onUpdate={(event:any)=> {data.general.education = event; sendUp()}}
          />
          <Helper
            text="Your educational background expressed as course titles. If multiple, please specify."
            size="32px"
            borderRadius= "0px 3px 3px 0px"
          />
        </Row>


        <Row
          margin="8px 0px 8px 0px"
          padding="0px 0px 0px 44px"
          >
          <Input
          value={data.general.occupation}
            type="field"
            label="Occupation"
            placeholder="Your occupation..."
            fieldWidth="400px"
            labelWidth="180px"
            onUpdate={(event:any)=> {data.general.occupation = event; sendUp()}}
          />
          <Helper
            text="Input you occupation; If student please input your degree (i.e. MArch Architecture)."
            size="32px"
            borderRadius= "0px 3px 3px 0px"
          />
        </Row>

        <Row
          margin="8px 0px 8px 0px"
          padding="0px 0px 0px 44px"
          >
          <Input
            value={data.general.creative_practice}
            type="field"
            label="Design Practice"
            placeholder="i.e. Part II Architectural Assistant [6 moths]"
            fieldWidth="400px"
            labelWidth="180px"
            onUpdate={(event:any)=> {data.general.creative_practice = event; sendUp()}}
          />
          <Helper
            text="How long you held a full-time job in architecture or in a design related profession such as architecture, engineering, graphical design, etc. If multiple, please specify."
            size="32px"
            borderRadius= "0px 3px 3px 0px"
          />
        </Row>


        <Row
          margin="8px 0px 8px 0px"
          padding="0px 0px 0px 44px"
          >
          <Input
            type="dropdown"
            label="Emotional State"
            fieldWidth="400px"
            labelWidth="180px"
            options={["", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10"]}
            onUpdate={(event:any)=> {data.general.emotional_state = event; sendUp()}}
          />
          <Helper
            text="Rate how calm you are from a scale 1-10 one being depressed and 10 being joyful [your current emotional state]."
            size="32px"
            borderRadius= "0px 3px 3px 0px"
          />
        </Row>

        <Row
          margin="8px 0px 8px 0px"
          padding="0px 0px 0px 44px"
          >
          <Input
            type="field"
            label="Birth order"
            fieldWidth="400px"
            labelWidth="180px"
            placeholder="i.e. Firstborn / Other / Unknown."
            onUpdate={(event:any)=> {data.general.birth_order = event; sendUp()}}
          />
          <Helper
            text="Are you a firstborn or the only child in your family?"
            size="32px"
            borderRadius= "0px 3px 3px 0px"
          />
        </Row>
      </div>

      <Row margin="10px 0px 10px 0px">
        <Action
          isActive={isComplete}
          label="Next"
          margin="0px 0px 0px auto"
          onClick={()=> props.slideForrward()}
        />
      </Row>
    </div>
  )
}
